### PR TITLE
Dress up the engine!

### PR DESCRIPTION
**Pull request by thopiekar**
Looks like that:

image

Is a mixture of the Cura icon + Terminal icon from the Breeze project.

Fixes: #661

### CODE REVIEW

**Comment by krop** [comment]
You didn't add the license file for the breeze icon you use. Please also contact the copyright holder to check whether he accepts his work to be part of another icon.

**Comment by thopiekar** [comment]
Good point. Only wanted to wait for feedback on this from the Ultimaker developers.

By the way, do you know how to add the licence correctly? Never put things together from other projects like this before.

**Comment by krop** [comment]
The breeze icons tarball contain the license file (called COPYING-ICONS). Since you want to create a derivative work with one of these icons, you also need the author's agreement.

**Comment by thopiekar** [comment]
Ok, thanks. So before this gets merged we have to care about getting either the agreement or designing our own icon.

Or could there already be consequences?

**Comment by krop** [comment]
No, it's WIP. Just don't merge it until everything is sorted

**Comment by Ghostkeeper** [comment]
Since Ultimaker will be publishing this executable and Ultimaker is licensed to use the icon, I don't foresee any licensing problems (as long as it is indeed the original Cura icon).

**Comment by thopiekar** [comment]
He meant the console icon I embedded on top of the Cura icon.

**Comment by Ghostkeeper** [comment]
Ah, I see. I thought that was an addition from your OS or something.

Maybe we can use the normal Cura icon for now and we'll see about getting a new icon for the engine.

**Comment by thieraufc** [comment]
I'm no artist so feel free to shoot this down, but here's something I put together. I modified the existing cura logo found in [the cura repository](https://github.com/Ultimaker/Cura/blob/master/icons/cura-128.png). It's the cura logo with a terminal image in the same style:
cura-128
Because it's modified from an LGPL repository, there shouldn't be any licensing issues there or here.

**Comment by Ghostkeeper** [comment]
I like the idea of that icon. The layout needs some work though. But for now I think we'll keep ourselves to the original PR.

**Comment by ianpaschal** [comment]
Switched icon to use a gear in the C (see below). Discussed and voted upon internally.

icon_1024

**Pull request merged**
