### PR TITLE
fix: zigzaggify should put connections next to border, not on it

### PR DESCRIPTION
**Pull request by BagelOrb**
These fixes are cherry-picked from https://github.com/Ultimaker/CuraEngine/pull/767

### CODE REVIEW

**Comment by BagelOrb** [comment]
Before:
image

After:
image

**Comment by BagelOrb** [comment]
The problem seems mostly fixed by a commit by you: 5fa54dcfdb94b1eae0c443715cfb4b943f2b242c

**Comment by BagelOrb** [comment]
Your fix is incorrect and introduces problems for cross infill.

The outline_offset is defined as the offset to obtain the outline of the area to fill with infill, so it's the Infill class who should be respondible for performing the correct offset, it should not be the caller who is responsible for fixing zigzag infill by providing different parameters.

**Comment by BagelOrb** [comment]
Before:
image


After:
image

**Comment by jackha** [comment]
Devs, see: CURA-5397

**Comment by ianpaschal** [comment]
Code looks fine to me. Second opinion @Ghostkeeper?

**Pull request merged**
