### PR TITLE
Add setting for Support Infill Line Direction

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR makes the orientation of infill lines settable. It fixes https://github.com/Ultimaker/Cura/issues/3481

Also see the matching PR for the frontend: https://github.com/Ultimaker/Cura/pull/4212

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Well that was simple enough :P Thanks!

**Comment by diegopradogesto** [comment]
Thanks for the contribution.
Devs. CURA-5635

**Comment by fieldOfView** [comment]
I'll check it out.

**Comment by fieldOfView** [comment]
Sorry, that was a silly mistake; The setting is set in degrees instead of radians.

**Comment by alekseisasin** [comment]
Now it works, I left a short message in Cura Pull Request, could you check.

**Pull request merged**
