### PR TITLE
Implement wall_overhang_fan_speed to override fan speed while printing overhung walls.

### PR DESCRIPTION
**Pull request by smartavionics**
Allow overhung wall lines to have their own cooling fan speed.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
What use case would you have in mind for this feature?

**Comment by smartavionics** [comment]
Being able to alter the fan speed while printing overhung walls was a feature request when the wall overhang detection was introduced.

**Comment by akshaal** [comment]
@smartavionics why did you close your own PR? This sounds like quite a useful feature for printing with filaments that can't be cooled all the time (PETG, ABS) but still need cooling for printing overhungs. I know that you have the feature in your fork, just curious why not here..

**Comment by smartavionics** [comment]
Hi @akshaal , I can't remember now, that was so long ago. Anyway, I am no longer contributing new features to Cura, only bug fixes.

**Pull request closed without merging**
