### PR TITLE
Code reviewing. Fix out of bounds array and lost checks for segments ended with mesh vertice.

### PR DESCRIPTION
**Pull request by skarasov**
Code reviewing.
Fix out of bounds array and lost checks for segments ended with mesh vertice.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
I didn't see this pull request yet and fixed the out of bounds array myself too, from your comment. However this review fixes a number of different small issues as well, so it would still be good to merge.

Only... You re-added a few if statements that I also removed from a different comment of yours. Indeed these if-statements can never be true and they are no longer necessary, so they shouldn't be added back. Could you remove them?

**Comment by skarasov** [comment]
No. In #1313 you move ">=z" from one if-statement to another. That's why `if (p2.z == z)` became never true.
My point was - checks for segment ending on mesh vertice shoud also be moved. Not to completely remove them.
This request fix it.

**Comment by Ghostkeeper** [comment]
Indeed it appears that `endVertex` now always remains on nullptr. I was confused by the Github code review page because it had left precisely the contents of an if-statement out in its diff view, showing the wrong if-statement above the changed code. Sorry. We need to check each of the if-statements to see if `endVertex` is set correctly if ending exactly on a 3D vertex. This variable is used for stitching. This PR is expected to fix that.

**Review by Ghostkeeper — APPROVED** [review]

**Comment by Ghostkeeper** [comment]
Thanks for paying attention!

**Pull request merged**
