### PR TITLE
Feat woodfill

### PR DESCRIPTION
**Pull request by BagelOrb**
Looks nice.

Works very well if you set the Top Surface Layers to 1, set the Top Surface Pattern to Concentric and set the Speckle Density to something like 5 speckles per square centimeter.

image

### CODE REVIEW

**Comment by nallath** [comment]
And the point of this is?

**Comment by BagelOrb** [comment]
> And the point of this is?

Aesthetics.

**Comment by BagelOrb** [comment]
"aesthetics"

**Comment by BagelOrb** [comment]
Maybe my bed wasnt really level.

here's another print:


With connect top/bottom polygons enabled (on the branch where the feature is fixed).

**Comment by BagelOrb** [comment]
Maybe this feature is just not cool enough, that's okay.

But don't act like aesthetics is not a valid reason for wanting some type of top/bottom pattern.

**Comment by BagelOrb** [comment]
I don't think this is pretty any more.

**Pull request closed without merging**
