### PR TITLE
Stringtest: Making it 64bit-save

### PR DESCRIPTION
**Pull request by thopiekar**
Big thanks to the Debian community for the patch and to @onitake for picking up this patch!
Here follows the original description of the patch:

Description: Correct writeInt2mmAssert() to work with int64_t
 The writeInt2mmAssert() method in tests/utils/StringTest.cpp uses
 the wrong printf formatting string when printing int64_t.
Author: Petter Reinholdtsen <pere@hungry.com>
Forwarded: no
Reviewed-By: Petter Reinholdtsen <pere@hungry.com>
Last-Update: 2017-10-07

* Source: https://anonscm.debian.org/cgit/3dprinter/packages/cura-engine.git/tree/debian/patches/1000-64-bit-safe-stringtest.patch

### CODE REVIEW

**Comment by onitake** [comment]
You should add
```
#include <cinttypes>
```
or
```
#include <inttypes.h>
```
at the top.

**Comment by LipuFei** [comment]
This is C++, so `#include <cinttypes>`

**Comment by thopiekar** [comment]
i386:

dh_auto_test || true
	make -j4 test ARGS\+=-j4
make[2]: Entering directory '/<<PKGBUILDDIR>>/obj-i686-linux-gnu'
Running tests...
/usr/bin/ctest --force-new-ctest-process -j4
Test project /<<PKGBUILDDIR>>/obj-i686-linux-gnu
    Start 1: SpaceFillingTreeFillTest
    Start 2: SparseGridTest
    Start 3: IntPointTest
    Start 4: LinearAlg2DTest
1/7 Test #1: SpaceFillingTreeFillTest .........   Passed    0.01 sec
2/7 Test #2: SparseGridTest ...................   Passed    0.01 sec
3/7 Test #3: IntPointTest .....................   Passed    0.00 sec
4/7 Test #4: LinearAlg2DTest ..................   Passed    0.00 sec
    Start 5: PolygonUtilsTest
    Start 6: PolygonTest
    Start 7: StringTest
5/7 Test #7: StringTest .......................   Passed    0.00 sec
6/7 Test #6: PolygonTest ......................   Passed    0.01 sec
7/7 Test #5: PolygonUtilsTest .................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) =   0.02 sec
make[2]: Leaving directory '/<<PKGBUILDDIR>>/obj-i686-linux-gnu'
make[1]: Leaving directory '/<<PKGBUILDDIR>>'

- https://code.launchpad.net/~thopiekar/+archive/ubuntu/cura-master/+build/13562640/+files/buildlog_ubuntu-artful-i386.cura-engine_1%3A3.0.99-master~201710100808~rev1752~pkg172~ubuntu17.10.1_BUILDING.txt.gz

armhf:

dh_auto_test || true
	make -j4 test ARGS\+=-j4
make[2]: Entering directory '/<<PKGBUILDDIR>>/obj-arm-linux-gnueabihf'
Running tests...
/usr/bin/ctest --force-new-ctest-process -j4
Test project /<<PKGBUILDDIR>>/obj-arm-linux-gnueabihf
    Start 1: SpaceFillingTreeFillTest
    Start 2: SparseGridTest
    Start 3: IntPointTest
    Start 4: LinearAlg2DTest
1/7 Test #1: SpaceFillingTreeFillTest .........   Passed    0.01 sec
2/7 Test #3: IntPointTest .....................   Passed    0.01 sec
3/7 Test #2: SparseGridTest ...................   Passed    0.01 sec
4/7 Test #4: LinearAlg2DTest ..................   Passed    0.01 sec
    Start 5: PolygonUtilsTest
    Start 6: PolygonTest
    Start 7: StringTest
5/7 Test #7: StringTest .......................   Passed    0.01 sec
6/7 Test #6: PolygonTest ......................   Passed    0.01 sec
7/7 Test #5: PolygonUtilsTest .................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 7

Total Test time (real) =   0.04 sec
make[2]: Leaving directory '/<<PKGBUILDDIR>>/obj-arm-linux-gnueabihf'
make[1]: Leaving directory '/<<PKGBUILDDIR>>'

- https://launchpadlibrarian.net/340341214/buildlog_ubuntu-artful-armhf.cura-engine_1%3A3.0.99-master~201710100808~rev1752~pkg172~ubuntu17.10.1_BUILDING.txt.gz

**Comment by onitake** [comment]
I wonder why we didn't hit that error... Funny.

**Comment by thopiekar** [comment]
@onitake No problem.
But feel free to prepare directly commits and pull requests, if the other guy you are working with or you are finding solutions for some bugs.
Pull requests and improvements are always welcome! 🥇

**Comment by Ghostkeeper** [comment]
Actually, we've had that issue in `string.h` and ended up having to fix it differently. See this history:

* https://github.com/Ultimaker/CuraEngine/commit/58e2e1a4e111c6b410839685a45f578eb0722f43#diff-699dcb4d5312b48dd9a3705376a9a327
* https://github.com/Ultimaker/CuraEngine/commit/faab907babb88d9b84eaf0e56b35e9c02549cefd#diff-699dcb4d5312b48dd9a3705376a9a327
* https://github.com/Ultimaker/CuraEngine/commit/aa14682087494924ef6fe74efcad16e2bf4c18d3#diff-699dcb4d5312b48dd9a3705376a9a327
* https://github.com/Ultimaker/CuraEngine/commit/baeacf4a765628e220a25fb9255ddafc8c097bf3#diff-699dcb4d5312b48dd9a3705376a9a327
* https://github.com/Ultimaker/CuraEngine/commit/1f1c2c686d740c79e23c91aacee82b25347e571e#diff-699dcb4d5312b48dd9a3705376a9a327

I think we should fix this test in the same way. The writer itself doesn't support those high integers any more anyway.

**Comment by onitake** [comment]
So, @Ghostkeeper - the preferred fix would be to change the test to use int32_t instead of int64_t?

**Comment by Ghostkeeper** [comment]
Yes, and to then use `%d` since the `PRId64` gave other problems too.

**Comment by onitake** [comment]
Ok? Shouldn't these printf macros solve all problems?

Anyway, @thopiekar can you respin the patch to use `int32_t`?

**Comment by Ghostkeeper** [comment]
Apparently not. I don't remember exactly what bugs we found there and on which platform, but we had to change it in the g-code export code even though we also use `sprintf` there.

**Comment by thopiekar** [comment]
@onitake Done

**Comment by onitake** [comment]
You can remove the cinttypes include as well, if we're not using the macros.

And the `int64_t` is still there in `void StringTest::writeInt2mmAssert(int64_t in)`?

**Comment by Ghostkeeper** [comment]
I've merged this and removed the unused include.

**Comment by onitake** [comment]
@Ghostkeeper But you still kept the int64_t argument - I believe this was the main pain point. Can you remove that as well?

**Comment by Ghostkeeper** [comment]
Yeah I also removed that. I think something went wrong with pushing that change initially but here it is: https://github.com/Ultimaker/CuraEngine/commit/fe45e504ace024d920fe18b4f55d6aa07b2f929b

**Comment by onitake** [comment]
Great, thanks!

**Pull request merged**
