### PR TITLE
Implement speed/flow/fan settings for bridge regions

### PR DESCRIPTION
**Pull request by smartavionics**
Not yet a merge candidate but it is usable if people wish to try it out.

### CODE REVIEW

**Comment by smartavionics** [comment]
Associated Cura PR is https://github.com/Ultimaker/Cura/pull/3175.

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-67.

**Comment by ianpaschal** [comment]
Tested by myself and @jackha.

**Comment by smartavionics** [comment]
Hi @ianpaschal & @jackha, thanks for merging this quickly. Now the fun starts! Much testing is going to be needed to come up with suitable settings for the various materials/qualities.
If you come across any big problems, please contact me and I will fix ASAP.

**Comment by ianpaschal** [comment]
Yeah, to be honest my background is not even really in 3D printing; it's in product design and computer graphics, it was only a year ago that I started doing my thesis with a 3d printing company making CAD software and I've only been at Ultimaker for 2 months... soooo I still just use the stock profiles haha. But I twiddled your settings and did some prints and nothing exploded so... merged!

**Comment by Ellecross** [comment]
Hey @smartavionics, I've enabled the bridge settings on a different model [flat_bridge.zip](https://github.com/Ultimaker/CuraEngine/files/1803019/flat_bridge.zip) and the print looked really stringy compared to the same print without it. 

**Here are sample images:** 
img_20180312_145521398

img_20180312_145537374

img_20180312_145603999

Is this because the model I used have the bases too far apart? I've used PLA AA0.4 with Fine quality settings.

**Comment by smartavionics** [comment]
That bridge isn't so long, my guess is that the default values for the bridge settings are not right. You will need to try different values for the speeds and flows, etc. Fan amount is critical too. Also, the direction of the fan has an influence (not that we can change that).

The first layer of the bridge should have no (or very few) broken strands and they should be separate and not stuck together.

**Pull request merged**
