### PR TITLE
cubicsubdiv windows fix

### PR DESCRIPTION
**Pull request by mboerwinkle**
This fixes my cubicsubdiv when cross-compiled and run in wine. I'm not completely sure why this works, but it basically ends up passing and comparing smaller values. Should be good enough for now to get the beta build working again.

### CODE REVIEW

**Comment by BagelOrb** [comment]
Nice!

We're kind of busy with a lot of stuff at the moment, but we'll merge this ASAP.

**Comment by mboerwinkle** [comment]
The problem seems to have been caused by different definitions of "long int". Specifying "int64_t" for sphere_slice_radius2 was all it needed. I have tested from Windows 10 and Wine. I have updated the pull request.

**Comment by BagelOrb** [comment]
I didn't want the CMakeLists changes and all in the history, so I've fixed it myself: https://github.com/Ultimaker/CuraEngine/commit/113202cd3466f9db05f7125d12f8b9b1b3542993

`coord_t` evaluates to `long long singed int`.
An int is good enough for a layer_nr. There can't be that many layers.

**Comment by BagelOrb** [comment]
Now I only have to check whether this actually solves the problem on our test machines.

**Pull request closed without merging**
