### PR TITLE
CURA-5777 Fix point operators

### PR DESCRIPTION
**Pull request by LipuFei**
Because Point is a clipperlib point, which has a constructor Point(int x = 0, int y = 0), which can implicitly convert a int/unsigned int "c" to a Point(c, y = 0), and this causes undesired behaviour. So, we remove
the /= and *= operators in Point to avoid this implicit conversion to happen.

### CODE REVIEW

**Comment by rburema** [comment]
@LipuFei Did you add the extra documentation that was added to the 3.5.1-version of this PR here as well? I can't find it right now.

**Comment by LipuFei** [comment]
@rburema We can merge 3.5 back to master then the doc there will be in as well. Or you can also cherry-pick that doc commit.

**Comment by rburema** [comment]
@LipuFei Good point. Let's wait for the 3.5 merge then, by then the build-server will be able to do the checks for master again as well.

**Comment by LipuFei** [comment]
Well... There's no need to merge this I guess. Those changes are in `master` already.

**Pull request closed without merging**
