### PR TITLE
Prime amount was incorrect when relative extrusion and firmware retract both enabled.

### LINKED ISSUE #761: Firmware Retract + Relative Extrusion + Coasting leads to enormous primes
**Application Version**
`Cura-3.3.1.AppEngine`

**Platform**
Arch Linux

**Display Driver**
Nouveau

**Steps to Reproduce**
1. Enable Firmware Retract
2. Enable Coasting
3. Enable Relative Extrusion
4. Slice a STL

**Actual Results**
GCode will contain something like this:
```
G11
G1 F1800 E113.40642
```
which means do firmware unretract and (remember relative extrusion) extrude another 113.40642mm of filament right at this spot.

**Expected results**
Amount of priming should be relative.

**Additional information**
The issue will not occur if Coasting is disabled (tested this) and probably not when absolute extrusion is used (I only assume that).

### PR DESCRIPTION
**Pull request by smartavionics**
Fixes #761.

### CODE REVIEW

**Comment by Appesteijn** [comment]
CURA-5375

**Comment by Vandrasc** [comment]
Hi @smartavionics , sorry for coming back to this ticket, it was a while ago. I was trying to reproduce the issue and compare two types G-code before and after the merge and I don't see any difference. Could you please give a tip on how to distinguish the fix?

**Comment by smartavionics** [comment]
Hi, I'm struggling to remember what model/project was used to test this. Let me have a search, I'll get back to you....

**Comment by smartavionics** [comment]
So as the OP says, you need to enable firmware retraction, relative extrusion and coasting. When I do that I get this output snippet without the PR:

````
G10
G1 F18000 Z0.8
G0 X-18.736 Y-15.993 Z0.8
;TYPE:SUPPORT
G1 F18000 Z0.3
G11
G1 F1800 E35.45939
````

And this with the PR:
````
G10
G1 F18000 Z0.8
G0 X-18.736 Y-15.993 Z0.8
;TYPE:SUPPORT
G1 F18000 Z0.3
G11
G1 F1800 E0.02657
````

If I diff the before, after gcode files I get stuff like this:

````
267c267
< G1 F1800 E35.45939
---
> G1 F1800 E0.02657
415c415
< G1 F1800 E39.90851
---
> G1 F1800 E0.02657
630c630
< G1 F1800 E54.17805
---
> G1 F1800 E0.02657
722c722
< G1 F1800 E57.71812
---
> G1 F1800 E0.02657
````
And so on.

I think the PR is doing what it should as far as I can tell.

**Comment by Vandrasc** [comment]
Sorry for wasting your time, I did not look in the original ticket (#761), so coasting was disabled for me. 

I do see the G1 F commands now. 
Thank you!

**Comment by smartavionics** [comment]
No problem, cheers!

**Pull request merged**
