### PR TITLE
Enhance wall order optimiser to use combed distances for inner walls (+ bug fixes)

### PR DESCRIPTION
**Pull request by smartavionics**
This PR changes the wall print order optimiser to use combed distances when ordering inner walls. Previously, it used combed distances for outer walls but now it uses combed distances for both outer and inner walls.

It also fixes some other related issues.

Provides the solution for the issue discussed in https://github.com/Ultimaker/Cura/issues/4157

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-5914.

**Comment by smartavionics** [comment]
So, folks. Not really hassling here, more like just getting a feel for how things are progressing. Do you have any intention of using this and/or the other PRs that are currently queued up? Seems there hasn't been much attention paid to any of them for some time now. Thanks.

**Comment by Ghostkeeper** [comment]
They are still queued up and we still intend to merge them (except the ones we closed).

It seems as though we have a neverending stream of high-priority issues though, especially new issues arising from features that we or other teams in Ultimaker built. It doesn't help that we're down 2 developers since last December. Once in a while we get to a point where we get a chance to work on one or two of these old PRs, like this one last week: https://github.com/Ultimaker/CuraEngine/pull/892. The easy PRs are usually done pretty quickly somewhere in between by people not adhering strictly to our ticket priority. The rest linger.

**Comment by smartavionics** [comment]
OK, thanks for the reply, that's pretty much what I expected. Anyway, I encourage the team to try and process these PRs as they are mostly about improving gcode quality and fixing bugs rather than adding new features.

**Comment by smartavionics** [comment]
All my PRs are so old now, I can't remember what's in them. I no longer care whether you use them or not.

**Comment by smartavionics** [comment]
Closing this as you have decided not to use it.

**Pull request closed without merging**
