### PR TITLE
When z-seam is located on sharpest corner align z-seam of single hole with outline z-seam.

### PR DESCRIPTION
**Pull request by smartavionics**
When printing parts that have a single hole that is close to the outline (e.g. a tube with
thin walls), it's nicer to have the z-seam of the hole aligned with the z-seam of the outer
wall. This happens for free when the z-seam type is nearest or user-specified but when
the z-seam type is sharpest corner, the z-seams for the hole and the outside wall don't
have to coincide. This mod handles that scenario and forces the z-seam of the hole to match
the z-seam of the outer wall.
Compare, without this mod:
screenshot_2017-10-28_15-41-28

and, with this mod:
screenshot_2017-10-28_15-41-09

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
What happens when your example above has a dent somewhere in the outer wall and another dent somewhere in the inner wall but at a different position? Looking briefly at the code, it would move them together, defeating the setting of sharpest corner for one of the seams.

In my opinion this should only kick in if the corners all have the same angle, such that which corner is sharpest is ambiguous. And I'm not sure if that slim use case is worth the processing power.

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-4534.

**Comment by smartavionics** [comment]
> What happens when your example above has a dent somewhere in the outside wall and another dent somewhere in the inside wall but at a different position? Looking briefly at the code, it would move them together, defeating the setting of sharpest corner for one of the seams.

That's why it requires the walls to be pretty close together, if the walls are spaced far enough apart to allow appreciable dents, this tweak should not be triggered (that's the hope!)

**Comment by alekseisasin** [comment]
@smartavionics , Hi, I tried to make a different models to get result which you showed on second image, I only see that infill and inner wall start apth close to each other, but the outer wall starts is not, Did try with different diameters.

**Comment by smartavionics** [comment]
Hi, if the wall of the part are thick enough to have infill then the seams will not be aligned. This PR is really about stopping an unnecessary retract when printing tubes whose walls are thin.

**Comment by LipuFei** [comment]
Hi @smartavionics , I tried to reproduce the result you have *without* your mod, but I can only get something like this:
image
There are many travel moves between the walls and there are only walls.

I merged with the latest master. Maybe some code in master broke something?

**Comment by smartavionics** [comment]
You do need to have the wall order optimization enabled? I get the same as you do if I disable it.

**Pull request merged**
