### PR TITLE
MSVC Compatibility

### PR DESCRIPTION
**Pull request by bjude**
This PR reintroduces compatibility with MSVC for compiling CuraEngine.

Changes made are summarised in each commit but broadly these are the changes:
- Replace variable length arrays with calls to alloca()
- Replace __WIN32 macros with _WIN32
- Add conditionals to CMakeLists.txt so we have comparable compile flags under MSVC vs GCC
- A couple of include fixes
- Change some OpenMP constructs to account for the old version that MSVC uses

I've tested the build using VS 2017, MinGW GCC 8.1 (under MSYS2) and GCC 8.2 (under windows subsystem for linux). I've tested the MSVC-built binary using Cura 3.4 but haven't tested the MinGW or GCC builds (beyond verifying that they build successfully)

### CODE REVIEW

**Comment by bjude** [comment]
Is there any interest in this PR? There was interest in a previous PR that did a similar result that was closed because it had merge conflicts

**Comment by bjude** [comment]
Is there any interest in this having CE compilable under MSVC? In a previous PR that did a similar thing (#383) @Ghostkeeper  mentioned that he had made a ticket internally about MSVC compatibility but there doesnt seem to be much appetite at Ultimaker for this PR

**Comment by bjude** [comment]
Is there interest in having CE compilable under MSVC? In a previous PR (#383), @Ghostkeeper mentioned they created a ticket internally at Ultimaker but it was closed for lack of activity.

This PR could use some cleanup and have some commits squashed which im happy to do, but only if theres appetite for merging.

**Comment by bjude** [comment]
Is there interest in having CE compilable under MSVC? In a previous PR (#383), @Ghostkeeper mentioned they created a ticket internally at Ultimaker but it was closed for lack of activity.

This PR could use some cleanup and have some commits squashed which im happy to do, but only if theres appetite for merging.

**Comment by bjude** [comment]
Is there interest in having CE compilable under MSVC? In a previous PR (#383), @Ghostkeeper mentioned they created a ticket internally at Ultimaker but it was closed for lack of activity.

This PR could use some cleanup and have some commits squashed which im happy to do, but only if theres appetite for merging.

**Comment by bjude** [comment]
Is there interest in having CE compilable under MSVC? In a previous PR (#383), @Ghostkeeper mentioned they created a ticket internally at Ultimaker but it was closed for lack of activity.

This PR could use some cleanup and have some commits squashed which im happy to do, but only if theres appetite for merging.

**Comment by bjude** [comment]
Is there interest in having CE compilable under MSVC? In a previous PR (#383), @Ghostkeeper mentioned they created a ticket internally at Ultimaker but it was closed for lack of activity.

This PR could use some cleanup and have some commits squashed which im happy to do, but only if theres appetite for merging.

**Comment by Ghostkeeper** [comment]
We're willing to add it, but we aren't testing with MSVC so there is a chance that we'll break it again.

(Developers, see CURA-6059.)

**Comment by diegopradogesto** [comment]
As @Ghostkeeper commented, we are not currently supporting it, but we don't have problem to add it. However we would like to ask you to add documentation in the README, so in case somebody wants to compile CuraEngine with MSVC, they will have enough information.

Please add this documentation and resolve the conflicts. Once done, we will take a look right away.

**Comment by bjude** [comment]
Documentation has been added to README.md and the branch is up to date with the master branch.

I haven't had a chance to run Cura using my branch since 38a6e95 but the only commits since then have been working around build errors and shouldn't affect functionality at all.

**Comment by rburema** [comment]
Hi @bjude,

Thanks for your hard work! :-)

It appearantly does not show up here on web, but I made a few small adjustments before merging:
 - deleted the duplicate `settings.cpp` (versus `Settings.cpp`, note case of first letter)
 - added comments to the fixed-size vector initializations, so people won't be pushing to those vec's later
 - clarified comments about MSVC not compiling because of unsigned integers (is an OpenMP issue, MS uses a very old version it seems)
 - deleted files that had been deleted in the meantime and would have been readded by the eventual merge

I also ran into a few issues while trying to do a complete MSVC build (which includes the libraries), but I think I got a few settings crossed. I should really continue with otther stuff now, so I'll try again later. _Again it's probably on my end_, but:
 - A reference to pthread.lib was there when I buld the `.sln`.
 - Some /MD <-> /MT issues (even more likely to be a problem on my side only).

Also, did you know:
 - You could technically also have fixed the `not`/`or` thing by including `<ciso646>` see [here]( https://en.cppreference.com/w/cpp/header/ciso646) and [here](https://en.cppreference.com/w/cpp/language/operator_alternative). Though it's so little known just replacing them is probably better.

cheers,
Remco.

**Comment by bjude** [comment]
Great!

* Glad you worked out the `settings.cpp` issue, i couldn't work out why there was a thousand line diff in one of the commits that apparently didn't affect anything.
* The pthread issue is weird, it's only referenced in CMakeLists.txt [here](https://github.com/Ultimaker/CuraEngine/blob/cf1a3515fe618e0cd5b90378868840a2dda97503/CMakeLists.txt#L290) but the UNIX check should hide it. Are you running CMake from MSYS?
* /MD vs /MT is forever a problem, which libraries were conflicting?

Are there plans to add MSVC to the CI build (once the above issues are ironed out)?

**Comment by Ghostkeeper** [comment]
I don't think we'll do that, unless we choose to switch compilers for Windows entirely. It's work enough to keep up one compiler for every platform.

**Comment by rburema** [comment]
hi @bjude,
I'm running CMake from PowerShell (or occasionally the VS/native tools cmd). Not sure what happened there.

MD/MT: I didn't recompile all libraries for this, since I've had to make them with MSVC before. Some settings must've been messed with there.
cheers, Remco.

**Pull request merged**
