### PR TITLE
Use retract on skins

### PR DESCRIPTION
**Pull request by presslab-us**
Using combing on skins causes unsightly scarring on flat surfaces.
By forcing a retract between travel moves we can lift the head
above the surface to avoid this.

### CODE REVIEW

**Comment by BagelOrb** [comment]
A lot of retraction can cause the feeder to dig into the filament, leading to underextrusion or no extrusion at all. Did you implement the change as an option? Or did you change the code such that restraction always occurs?

**Comment by daid** [comment]
I don't think this is the proper solution at all. First off, it's not configurable as @BagelOrb mentions.
Secondly, it forces retraction on every single move, which only isn't grinding your filament to a total flat pieces because of the "retractionMinimalDistance". Which some people set to 0.

**Comment by presslab-us** [comment]
How would you like it to work?

**Comment by BagelOrb** [comment]
There are a number of possible solutions.
A good solution would be to perform combing along the inside of the polygon, instead of the outside border. 
However, it is very hard to think of a suitable algorithm to find a path on the inside which can't fail and which doesn't take an extraordinary amount of time (like O^2).

As of yet there is no workable alternative. Can you think of any?

**Comment by presslab-us** [comment]
Is combing preferred to retractions?  I realize each has it's own advantages...  But I think retractions work pretty good these days, and are often faster than combing.  I think finding a way to make retractions sensical on skin layers would be a workable solution.

In response to @daid, what would happen if combing were turned off with a retractionMinimalDistance of 0?  It seems like this would produce a retraction for every line of skin, as the code is now.  A way around this is to have a different minimal distance for the skin.  But this is a bad solution for a few reasons, and I think adding more options to the slicer is bad unless absolutely necessary.  Any additions should "just work" if possible.

**Comment by presslab-us** [comment]
I have updated my branch, allowing this change to be configured.  Please let me know what you guys think, and if it's not acceptable let me know how you would like it to look.  I have modified Cura also, and can submit a pull request for that once this one is completed.

**Pull request merged**
