### PR TITLE
Fix brim wall order bug

### PR DESCRIPTION
**Pull request by smartavionics**
Replacement for https://github.com/Ultimaker/CuraEngine/commit/2cdd76160f1c4574a20e29b560afd1f0b13d2c8d 

It's better to fix the bug in the optimizer than to avoid using the optimizer!

### CODE REVIEW

**Comment by diegopradogesto** [comment]
This is what I get working with your branch:
image

**Comment by smartavionics** [comment]
Hmm, I haven't touched the brim code. That's weird...

**Comment by diegopradogesto** [comment]
It happens in UM3 but not in Custom FDM printer. Maybe because other settings are affecting.

**Comment by smartavionics** [comment]
OK, I will check using UM3 and get back...

**Comment by smartavionics** [comment]
It still screws up even when the wall optimization is not enabled so it can't be the optimizer that's failing.

**Comment by smartavionics** [comment]
246ed65c3733dc709d10966eeb07020beb02db72 is the culprit!

**Comment by smartavionics** [comment]
Over to you @Ghostkeeper...

**Comment by smartavionics** [comment]
I fixed the regression introduced in 246ed65 (see https://github.com/Ultimaker/CuraEngine/pull/752).

**Comment by smartavionics** [comment]
Great, thanks!

**Comment by diegopradogesto** [comment]
Thank you!

**Pull request merged**
