### PR TITLE
[bug fix] Correct optimisation in combing path generation that can cut corners.

### PR DESCRIPTION
**Pull request by smartavionics**
It would be good if this could be merged ASAP as it can cause combing travels to cut corners.

### CODE REVIEW

**Comment by smartavionics** [comment]
I have reinstated the optimisation and fixed the problem by ensuring that the length of the fwd path is correct before comparing the reverse path length to it. This is better than just dropping the optimisation completely.

**Comment by smartavionics** [comment]
Without this PR, you can get unretracted travels that cut across holes, like this:

screenshot_2018-10-10_07-43-20

With the PR, only travels that use retraction will cross a hole:

screenshot_2018-10-10_07-44-36

**Comment by smartavionics** [comment]
You really want to be including this in 3.5.1.

**Comment by alekseisasin** [comment]
Hi @smartavionics , can you please share your model?

**Comment by smartavionics** [comment]
[UMS5_Pocket Tool Box V2.zip](https://github.com/Ultimaker/CuraEngine/files/2479190/UMS5_Pocket.Tool.Box.V2.zip)

**Comment by alekseisasin** [comment]
I will be added to 3.5.1. Thank you.

**Pull request merged**
