### PR TITLE
feat: force layer to start with given model

### PR DESCRIPTION
**Pull request by BagelOrb**
force a specific model to be the first to be printed with the current extruder on that layer

### CODE REVIEW

**Comment by BagelOrb** [comment]
See also https://github.com/Ultimaker/Cura/pull/2142

**Comment by BagelOrb** [comment]
@Devs see CURA-4073

**Comment by rburema** [comment]
@BagelOrb Going through stale branches right now: can this one be deleted?

**Comment by BagelOrb** [comment]
It's an unmerged feature and I think we decided back then we didn't want the feature after all.

Some people like the feature, though.

See the linked frontend PR.

**Comment by rburema** [comment]
I'm only deleting things if there isn't any work in there that could be used, so I'll leave this for now.

**Pull request closed without merging**
