### PR TITLE
Omit start temp if already in starting gcode

### PR DESCRIPTION
**Pull request by markwal**
so that it can participate in token expansion. See #240 

This change has a dependent corresponding change to Cura which is pull request Ultimaker/CuraEngine#490

### CODE REVIEW

**Comment by BagelOrb** [comment]
You just deleted all the logic around temperatures!
If you just include the temperature commands in the start gcode setting, then dual extrusion printers will end up with both nozzles heated all the time, unless you change the start gcode setting per print job.

The way it is now only nozzles which are used are heated.

Did you include such functionality in the frontend?

**Comment by markwal** [comment]
I tried to.  It loops across the objects and only generates commands for referenced extruders.  But I'm not sure I followed how the per object settings get set properly.  https://github.com/Ultimaker/Cura/pull/490/files#diff-81af33b9376386b0e7e43b8470fb209aR357

**Comment by markwal** [comment]
Updated Ultimaker/Cura#490 to move logic to slice job created by @awhiemstra and rebased to master

**Comment by markwal** [comment]
@BagelOrb Ultimaker/Cura#490 got merged.  And now this change is the simpler one that you proposed there.

**Comment by BagelOrb** [comment]
Feedback:
- I had to fix some style issues concerning braces (https://github.com/Ultimaker/CuraEngine/commit/9c8e32f37bcfb055597b0554cf82abcf1b5db1fa)
- I don't really see why you introduced material_print_temp_wait. Could it be that strictly viewed this is a separate issue?
- material_print_temp_wait and material_bed_temp_wait were not in the json. ***Every*** setting passed to the backend should be in the json.

**Comment by BagelOrb** [comment]
correction:
- material_print_temp_prepend and material_bed_temp_prepend were not in the json

**Comment by markwal** [comment]
I added the wait ones because you told me to in your first comment on Ultimaker/Cura#490.  You may have offered that then because the original proposed change introduced new placeholders separately for temp set and waits.

I didn't add the prepends because I was always computing them, based on whether temperature expansions occur in the start/end gcode and didn't realize that every setting should be in the json.

**Comment by BagelOrb** [comment]
Every setting should be in the json, so that CuraEngine knows they exist. When calling CuraEngine directly from the commandline, instead of via Cura frontend, CuraEngine uses the json file to get the default values of each setting.

As I understand your frontend code material_print_temp_prepend is set to false when the start gcode contains "{material_print_temperature}", whether it would be in an M104 or in an M109.
I would like it if CuraEngine would still prepend a wait-till-temp-is-reached command even though the start code already contained a set-temp-and-dont-wait command.
I think that's why I wanted the material_print_temp_prepend setting.

**Comment by markwal** [comment]
Ok, I'll edit the json to default prepend to true and do another PR. I see, definitely needed for the command line case.

**Comment by BagelOrb** [comment]
I included the settings in the json already, but thanks for the gesture!

**Comment by BagelOrb** [comment]
see https://github.com/Ultimaker/Cura/commit/94ee3882ad738d2de4c25b9c4cf7c8deb8f3d473

**Pull request merged**
