### PR TITLE
Implement cool_fan_lag setting.

### PR DESCRIPTION
**Pull request by smartavionics**
This PR makes print cooling fan speed overrides happen earlier so that the requested speed change has been achieved by the time the nozzle reaches the override zone.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
To be consistent with the structure of CuraEngine, this sort of thing would normally be implemented in the LayerPlanBuffer.

**Comment by smartavionics** [comment]
OK, let's forget it then,  I can't be bothered to haggle with you guys any more.

**Comment by Ghostkeeper** [comment]
Yeah, I'm sorry. It's just that we need to keep the code quality high, especially if there is a high ratio of contributions from outside vs. from the maintainers themselves, or we'll lose control over this code.

The LayerPlanBuffer was introduced in order to insert pre-heat commands in advance in order to make sure that an extruder has the correct temperature when necessary. That is the same use case as inserting fan speed commands in advance in order to make sure that a fan has the correct speed when necessary. It wouldn't make sense to implement that logic in two different places.

**Comment by smartavionics** [comment]
> That is the same use case as inserting fan speed commands in advance in order to make sure that a fan has the correct speed when necessary.

Actually, not true. The fan can change speed very much quicker than the nozzle can change temperature and so the granularity of the existing layer plan inserts mechanism is far too coarse. For optimal fan speed changes, you need to insert the fan commands within paths not on path boundaries.

**Pull request closed without merging**
