### PR TITLE
always retract when combing is disabled

### PR DESCRIPTION
**Pull request by fxtentacle**

### CODE REVIEW

**Comment by nallath** [comment]
And as always, thanks for the work :) It's much appreciated.

**Comment by BagelOrb** [comment]
Note: this has been merged into master as well: https://github.com/Ultimaker/CuraEngine/pull/244

**Comment by BagelOrb** [comment]
Currently this PR causes there to be retracts on moves as small as one micron.

You forgot the part which said
```if (!shorterThen(lastPosition - p, last_retraction_config->retraction_min_travel_distance))```

The code you introduced was already there about 10 lines above in the else-case for when combing failed. The only problem was that that piece of code was never executed when combing wasn't enabled, so now I just moved the code down and introduced a boolean variable which kept track of whether combing had occurred.

**Comment by BagelOrb** [comment]
BTW: I now fixed both our bugs ;)

**Pull request merged**
