### PR TITLE
Connect infill polygons

### PR DESCRIPTION
**Pull request by BagelOrb**
I declare war on retractions and travel moves.

image

This PR is suppoed to work really nicely with Multiply Infill: https://github.com/Ultimaker/CuraEngine/pull/767

### CODE REVIEW

**Comment by BagelOrb** [comment]
old:
image

new:
image

oh well...

**Comment by BagelOrb** [comment]
without Fill Gaps enabled...

old:
image


new:
image

Still not the best results.
Just wait untill the other feature also gets merged!

**Comment by rickyzhang82** [comment]
Can you explain the ideas how you find the starting point and how you sort/generate the path?

**Comment by BagelOrb** [comment]
It should be explained in the documentation of the code. Did you have a
look at the explanations in the code?

**Comment by rickyzhang82** [comment]
How can any sane human being read that many commit and figure it out your intention/algorithm? At least, this is not my style. Even I was called cow boy coder at work.

**Comment by BagelOrb** [comment]
Uhm yeah so we include documentation, so that you can understand the code
without reading the code.

I'm not gonna put my explanation in GitHub if I can also put the
explanation with the code itself.

Just have a look!

**Comment by rickyzhang82** [comment]
It is not presentation problem. It doesn't matter if this is from your phone or my 21inch monitor. 

What I saw is 30+ commits with encrypted text of commit message. I'd suggest the following:

- Rebase your PR when your send PR and remove any work-in-progress commit that makes no sense to others or nobody cares.
- Write a concise message in one line and a detailed message in **EVERY** commit. If you don't know how to do it, check out how Linux kernel repository.

TBH, failed to comply this can keep your job security. Continue practicing your cow boy style.

**Comment by BagelOrb** [comment]
I think commit messages are way less important than having documentation in
the code itself.

Let's hear from the Cura team itself how they feel about the idea of
rebasing and squashing commit and rewording commit messages and what not.

**Comment by rickyzhang82** [comment]
Fair enough. Thanks!

**Comment by Ghostkeeper** [comment]
Including documentation in the code is indeed much more valuable. Nobody is going to look at the commit messages for documentation, only for the reason why a change was made if they git blame. I don't think rebasing is necessary.

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-5399.

**Pull request merged**
