### PR TITLE
slicing mode

### PR DESCRIPTION
**Pull request by BagelOrb**
Options to determine how to slice a layer.

One of the reasons printed parts don't fit is because currently the middle of a layer is taken for the area of that layer, while that could mean half of the layer is sticking out of the model.

Exclusive:
[UM3N_cone_to_cylinder.3mf.txt](https://github.com/Ultimaker/CuraEngine/files/1364572/UM3N_cone_to_cylinder.3mf.txt)
image

Inclusive:
image

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Very cool, I actually did a small experiment with this about a year ago to see if we could make screw holes fit better.

**Comment by BagelOrb** [comment]
What was the result of your tests?

**Comment by ChrisTerBeke** [comment]
If you want your screws etc to fit, use exclusive mode. If you then design without margin (like injection molded parts would have), it fits quite nicely (ofc not perfect, but a lot better than using the default 'middle' model and add the margins in your design).

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-4459.

**Comment by alekseisasin** [comment]
I think the name for the setting "SlicingMode" is very general. I propose:
-> SlicingModeCompensation
-> SlicingModeCorrection

**Comment by ChrisTerBeke** [comment]
or "SlicingTolerance"?

**Comment by BagelOrb** [comment]
I prefer Slicing Tolerance. It really shows the user what you would use this for.

**Comment by ChrisTerBeke** [comment]
Not seeing any crashes anymore after latest changes.

**Pull request merged**
