### PR TITLE
Fix crash when definition has more extruder trains than extruder count

### PR DESCRIPTION
**Pull request by fieldOfView**
CuraEngine crashes when a definition defines more extruder trains in its def.json file metadata than specified in the machine_extruder_count setting. This PR fixes that crash, ignoring settings for the extra extruder_trains.

See https://github.com/Ultimaker/Cura/pull/1521 for a usecase of having a lower machine_extruder_count than defined extruder_trains: more easily defining printers with a variable number of extruder trains (eg custom dual- or quad-extrusion printers)

### CODE REVIEW

**Comment by LipuFei** [comment]
@fieldOfView just curious, so there's a concurrency issue with `FffProcessor::getInstance()->getSettingAsCount("machine_extruder_count")`?

**Comment by LipuFei** [comment]
Ah, sorry... I was thinking about something else...

**Comment by BagelOrb** [comment]
I can't imagine this fixes all problems for such a use case, but the code looks good this way...

**Comment by Ghostkeeper** [comment]
Seems to work fine, actually. I added a newline after the warning though because the logWarning doesn't do that by itself.

**Comment by fieldOfView** [comment]
@bagelorb: It took me quite a while of hunting for this one place where CuraEngine relies on the number of extruder definitions matches the machine_extruder_count. CuraEngine uses machine_extruder_count very consistently, kudos for that ;-)

**Comment by BagelOrb** [comment]
@fieldOfView are you kidding? Are you sarcastic? It couldn't possibly be the case that something is consistent in the engine! :D

**Comment by fieldOfView** [comment]
(by now I have found a way to fix the issue from Cura, but it never hurts to be defensive and fix it on both ends)

**Pull request merged**
