### PR TITLE
Fixed typo in LayerPlanBuffer.cpp. Closes: #724

### PR DESCRIPTION
**Pull request by onitake**

### CODE REVIEW

**Comment by smartavionics** [comment]
Are you sure this PR is necessary?

**Comment by ianpaschal** [comment]
I'd say it's good to fix it as long as the necessary changes are made.

**Comment by onitake** [comment]
OMG. I managed to mess up the patch myself. Mea culpa....
Sometimes I should just be patient.
I'll retract the PR. Would be nice if someone could fix this in a jiffy.

Thanks!

**Comment by diegopradogesto** [comment]
BTW, I change the typo in b2d34198f8af048dc5fe2d0438cae9c00188933c

**Comment by onitake** [comment]
Thanks, closing #724 .

**Pull request closed without merging**
