### PR TITLE
Use different skin pattern on first layer

### PR DESCRIPTION
**Pull request by 14bitVoid**
This pull req creates a setting to change the skin pattern for just the first layer. I like concentric skin for bed adhesion but not for anything else so this allows to set just the layer that does the bed adhesion to concentric.
I've used this for a while but now I decided to make a PR for it, it was tested on the Ultimaker 2 printer.

### CODE REVIEW

**Comment by BagelOrb** [comment]
There should be an accompanying PR on the frontend. Did you also submit changes to Cura/resources/definitions/fdmprinter.def.json ?

**Comment by BagelOrb** [comment]
Ah here it is: https://github.com/Ultimaker/Cura/pull/1290

**Comment by BagelOrb** [comment]
Looking good. Just checking whether `"top_bottom_pattern"` occurs anywhere else in the code besides these places.

**Comment by Ghostkeeper** [comment]
The only other place it's mentioned is here: https://github.com/Ultimaker/CuraEngine/blob/master/meta/15.04_to_2.0.txt#L174

**Comment by Ghostkeeper** [comment]
Works nicely. Thanks!

**Pull request merged**
