### PR TITLE
Bug fix when printing one at a time - move to next object location before waiting for bed temperature.

### PR DESCRIPTION
**Pull request by smartavionics**
It was waiting for the bed temperature to reach the first layer temp while the hotend
was still positioned on the top of the last part. Now it moves to the location of the next
part before waiting for the hotend to heat up.

Fixes issue reported at https://community.ultimaker.com/topic/22176-cura-321-is-melting-my-prints/

### CODE REVIEW

**Comment by smartavionics** [comment]
Also.. there is still another related bug because if the first layer nozzle temperature is different from the temperature used for the other layers, it is only used for the first part. For all the remaining parts, the nozzle temperature stays the same for all layers. This could cause problems with first layer adhesion?

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-5258.

**Comment by BagelOrb** [comment]
@Ghostkeeper do you mean you want @smartavionics to do that before you will consider merging this PR?

**Comment by smartavionics** [comment]
I know UM aren't keen on z movement but as this is only once per model I would have thought keeping the 5mm z-hop isn't going to be a big overhead and it keeps the nozzle out of the way?

**Pull request merged**
