### PR TITLE
WIP - Variable layer heights

### PR DESCRIPTION
**Pull request by ChrisTerBeke**
This is a WIP pull request for implementing variable layer heights. The PR is meant for others to keep track of the changes, add suggestions and discuss implementation details. Feel free to contribute!

### CODE REVIEW

**Comment by BagelOrb** [comment]
THe first 4 commits here are superfluous. You made a mistake somewhere.

**Comment by BagelOrb** [comment]
I recommend cherry picking the relevant commits to a new branch, which is branched off of master and force pushing that to this branch....

**Comment by ChrisTerBeke** [comment]
Yeah, doing that now. Not sure what's going on here, probably some older merges that were still on my machine.

**Comment by ChrisTerBeke** [comment]
Now in https://github.com/Ultimaker/CuraEngine/pull/649.

**Pull request closed without merging**
