### PR TITLE
Fix for bad bug that duplicates infill in skin support regions

### PR DESCRIPTION
**Pull request by smartavionics**
As discussed in https://github.com/smartavionics/Cura/issues/98.

I'm amazed this bug hasn't been spotted before now.

### CODE REVIEW

**Comment by rburema** [comment]
Hi again! Wanted to have a look at this one as well today (still). While I'm still going to argue for it's inclusion regardless (after I do some testing -- since the code is more correct), I can't seem to reproduce the original problem reported to your repo either for our 4.8 or our current main. Perhaps I am looking at the wrong thing? I don't see any duplicated infill lines in that project in layer 111 is what I'm saying.

**Comment by smartavionics** [comment]
It was definitely occurring when using my builds and I checked the UM master branch visually to see that the buggy code was there also so it should be affecting your builds as well. Maybe I goofed there. I will check again tomorrow.

**Comment by rburema** [comment]
The _code_ is definitely still there, yes. I'm just not seeing the behaviour. That could be on me though.

**Comment by smartavionics** [comment]
There's an easy way to check if the bug is occurring. See if the total filament distance changes when the same project is sliced with or without this PR in place. If the bug is there, the distance will increase.

**Comment by rburema** [comment]
> If the bug is there, the distance will increase.

I did just that. No difference.

@jellespijker you refactored a large part of this code recently. Do you have any opinion on how to proceed? I think it can do little harm and might be more correct, despite not solving a bug in our current code base. O.t.o.h. I don't want to mess with things too much if there's no real problem.

**Comment by jellespijker** [comment]
Yes I recently refactored a lot in this function. 
At a first glance (on my phone) I'm unsure about the clear() calls, since I seem to recall that multiply infill needs to store previous generated lines and polygons.
But that is just on top of my hat and without look at the code in the greater context.

I will take a look on Monday.

**Comment by jellespijker** [comment]
I can also not observe this behavior, certainly not with the original project file in smartavionics/Cura#98

The proposed fix changes the infill computations for infill which is positioned below the skin and needs an edge support layer. It is after all in the scope of the `if (hasSkinEdgeSupport)`  and not in the general Infill computation done on line 1650.  The original project file sets the skin edge support layers to 0. meaning that that specific infill computation isn't called.

I think that the original buggy behavior has been taken care of when I worked on CURA-7115 **Gradual Infill + Connect Infill = Overextrusion**

@rburema I agree with your reluctance to change this piece of code, certainly because these polygons and multiple infill instances are used by gradual infill, infill support, skin edge support layer, connected lines, connected polygons, and multiple features that rely on previously generated lines and polygons. Certainly, if the buggy behavior can't be replicated.

**Comment by smartavionics** [comment]
Just a thought, try not calling gcode_layer.optimizePaths() in FffGcodeWriter::processLayer() and see if the duplicate infill appears. It may be the optimization removes the duplicates? I don't use that function in my builds so that could be why I am seeing the duplicates and you are not.

**Comment by smartavionics** [comment]
I tried enabling the optimizePaths() function and it made no difference so ignore that idea.

**Comment by jellespijker** [comment]
I.m.o. it basically boils down to the question: _Is it a problem?_  
Since both @rburema and I can't reproduce the buggy behaviour, I'm inclined to say that we're trying to solve something here that doesn't need to be solved at this time.

**Comment by smartavionics** [comment]
Well, I guess time will tell...

**Comment by smartavionics** [comment]
I am still convinced there's a real problem here. I just tried using the current master branch of the CuraEngine (that's your master branch not my variant) and the issue is present without this PR and gone away with the PR. I can't explain why you are not seeing that.

**Comment by jellespijker** [comment]
@smartavionics could you share the project file, that shows this behavior? 

Because I'm really not seeing it and the fact that you do makes me a bit nervous and if it really is a bug that it should most certainly be fixed.

That being said I still find it strange that this fix targets the Infill instance used in creating the skin edge support area's. I would expect to be targeted at the Infill instance used for the "regular" infill.

**Comment by smartavionics** [comment]
Ah, in Infill::_generate(), if zig_zagify is true, for certain infill patterns, the result polygon is cleared first so I guess that's why you aren't seeing the problem.

**Comment by smartavionics** [comment]
Nope, it looks like that isn't it either, still looking...

**Comment by jellespijker** [comment]
@smartavionics you're persistent, I will certainly give you that ;-) 

I will give it a deeper look tomorrow if my agenda allows it. Otherwise, it will be the day after that.

**Comment by Ghostkeeper** [comment]
The bug does reproduce in Cura 4.8, but not just with the project file. The code changes made here are in a piece of code that only applies if Skin Edge Support is used, but it's set to 0 layers in that project file. Setting Skin Edge Support Layers to 1 reproduces the issue in layer 111.

The same doesn't apply for the Arachne branch because there the `infill_lines_here` variable doesn't get filled at all. Instead, the cut works by the segmentation of the infill area into `infill_below_skin` and `infill_not_below_skin`. The `infill_below_skin` is filled directly into `infill_lines` (not `infill_lines_here` any more) and the rest is printed when it generates the normal infill.

**Comment by jellespijker** [comment]
Thank you @Ghostkeeper for picking this up.

**Pull request closed without merging**
