### PR TITLE
Now combing travel moves longer than retraction_combing_max_distance use retraction.

### PR DESCRIPTION
**Pull request by smartavionics**
Engine mods for https://github.com/Ultimaker/Cura/pull/3477.

### CODE REVIEW

**Comment by Ghostkeeper** [comment]
Developers, see CURA-5118.

**Comment by smartavionics** [comment]
Wow, that was quick - LOL, it's only been there for around 6 weeks (just kidding, I know how busy everybody has been with new product stuff).

**Comment by jackha** [comment]
Haha it just crossed the thing I was working on. Don't take me wrong, it took a long time to figure out how combing works at all ;-)

**Comment by smartavionics** [comment]
You are now an invaluable member of the UM team as probably nobody else there knows how it all works. Ask for a rise!

**Pull request merged**
