### PR TITLE
Bug Fix: Zap short lines in gyroid connectors

### PR DESCRIPTION
**Pull request by smartavionics**
This PR stops very small (< 10 uM) line segments being created when the gyroid infill lines are connected. The small line segments are not really harmful as such but they screw up the chained lines detection and require extra travel moves so it's better if they are eradicated.

Before this PR you could get this:

screenshot_2018-10-11_08-48-35

There's a short line just above the kink in the infill to the left of the centre of the image.

With the PR it looks like this:

screenshot_2018-10-11_08-49-51

### CODE REVIEW

**Comment by damon-atkins** [comment]
@Ghostkeeper  any news on merging this code.

**Comment by Ghostkeeper** [comment]
Not yet. Due to a push on the GUI for the next version we're about 2 months behind. Bug fixes like these have a bigger chance to still make it in though.

**Comment by damon-atkins** [comment]
Hi @Ghostkeeper can I suggest you use Labels on pull requests to represent the teams thoughts like e.g.  AcceptedForReview or TarggetedForReview or NextRelease (or release number); P1 to P3; BugFix; Sev1.    Some opensource projects use labels to manage what must be in the current release a label it 3.1.

Giving positive feedback leads to more people providing help.      An **appearance** of not willing to accept changes leads to Forks and community separating, e.g. Best (or worst) example is OpenOffice. 

Cheers

**Comment by rburema** [comment]
Hi @smartavionics,
Sorry this took so long. Hopefully we've got some more time for PR's like these for a bit once 4.0 is out of the door.
cheers, Remco.

**Pull request merged**
