### PR TITLE
some optimization

### PR DESCRIPTION
**Pull request by masterhou**
1.load stl
2.use std::unordered_map instead of std::map
3.slicer, polygon close, find face by segment idx.
4.insert <k,v> fater than [k]=v;

### CODE REVIEW

**Comment by BagelOrb** [comment]
Im very inyerested in these optimizations! Cant wait tot review them on
monday. :D
Op 29 mei 2015 11:39 schreef "Thomas" <notifications@github.com>:

> 1.load stl
> 2.use std::unordered_map instead of std::map
> 3.slicer, polygon close, find face by segment idx.
> 4.insert fater than [k]=v;
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/Ultimaker/CuraEngine/pull/212
> Commit Summary
>
>    - some optimization
>
> File Changes
>
>    - *M* src/mesh.cpp
>    <https://github.com/Ultimaker/CuraEngine/pull/212/files#diff-0> (32)
>    - *M* src/mesh.h
>    <https://github.com/Ultimaker/CuraEngine/pull/212/files#diff-1> (5)
>    - *M* src/modelFile/modelFile.cpp
>    <https://github.com/Ultimaker/CuraEngine/pull/212/files#diff-2> (18)
>    - *M* src/settingRegistry.h
>    <https://github.com/Ultimaker/CuraEngine/pull/212/files#diff-3> (5)
>    - *M* src/settings.h
>    <https://github.com/Ultimaker/CuraEngine/pull/212/files#diff-4> (3)
>    - *M* src/slicer.cpp
>    <https://github.com/Ultimaker/CuraEngine/pull/212/files#diff-5> (20)
>    - *M* src/slicer.h
>    <https://github.com/Ultimaker/CuraEngine/pull/212/files#diff-6> (2)
>    - *M* src/utils/polygon.cpp
>    <https://github.com/Ultimaker/CuraEngine/pull/212/files#diff-7> (3)
>
> Patch Links:
>
>    - https://github.com/Ultimaker/CuraEngine/pull/212.patch
>    - https://github.com/Ultimaker/CuraEngine/pull/212.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ultimaker/CuraEngine/pull/212>.
>

-- 


IMAGINE IT >> MAKE IT

Meet us online at Twitter <http://twitter.com/ultimaker>, Facebook 
<http://facebook.com/ultimaker>, Google+ <http://google.com/+Ultimaker>

www.ultimaker.com

**Comment by Ghostkeeper** [comment]
The change of line 78 in polygon.cpp would cause the array to be initialised with random memory data, since that array is not static. The rest of it looks good to me from what I can see! Especially using unordered_map could give large speed improvements.

**Comment by BagelOrb** [comment]
Moreover, why do you initialize min_x with 0 instead of int.max?
It seems you meant to write 
std::fill_n(crossings, size(), 0);

please update this and the comments accordingly

**Comment by BagelOrb** [comment]
Did you test whether the output is the same for any given stl? Since these are only performance optimizations I would expect the generated gcode would be exactly the same.

**Pull request merged**
