### PR TITLE
Support gap filler fix

### PR DESCRIPTION
**Pull request by BagelOrb**
Some support lines had gone missing.

For example the line on the left here.
image
[zipped 3MF](https://github.com/Ultimaker/CuraEngine/files/8170140/SupportTest.zip)

When the Infill class generates any zigzag pattern then it performs an inset to the area so that the zigzag connectors don't overlap with the area to be filled, but lie half a line width inward. This inset can remove long thin areas which are then not filled anymore, which would be problematic for zizgag skin. The Infill class therefore generates gap filler lines for those areas removed.

However, it is not clear whether such gap filling areas also need to be filled when it comes to infill or support.

For support there could be a case made that if you don't use gap fillers then sometimes a thin overhang would not be supported. That's what this PR fixes.

However, for infill I see no reason to print gap fillers, since infill is generally allowed to be sparse. This is a TODO which is not fixed in this PR.

### CODE REVIEW

**Comment by BagelOrb** [comment]
See https://github.com/Ultimaker/CuraEngine/commit/ae378b240bbad9edd6f213529b9036e04b39bb1b#commitcomment-67796239

**Comment by MariskaMaas** [comment]
For Internal Use CURA-8995

**Comment by Ghostkeeper** [comment]
For comparison, this seems to be the problem that the fix is solving:
image

The support there is hanging in mid-air because it would be too thin to print with the 0.5 line width inset being done for zigzag.

**Comment by nallath** [comment]
Before the fix (project file, change profile to 0.15)
image

After the fix:

image

There is suddenly a floaty bit that wasn't there before.

**Review by nallath — CHANGES_REQUESTED** [review]
The fix seems to introduce a bug that should be fixed.

**Comment by BagelOrb** [comment]
This PR was to solve a hypothetical regression which was introduced in https://github.com/Ultimaker/CuraEngine/pull/1562, which built on https://github.com/Ultimaker/Cura/pull/11334.

When I checkout the master commit before that PR was merged (385e2ca6ce62af2b4b927d58352f378636418291 and checkout frontends with git checkout 'master@{Tue Feb 15 10:45:43 2022 +0100}') then we see the following behavior:
image

The gap filler for support was somehow not printed in the first place!

So this PR is trying to solve a bug which I thought I had introduced, but was already there in master before my Wall Ordering and polyline stitching PRs.

Do we want to print gap fillers for support in the first place??

**Comment by BagelOrb** [comment]
This is 4.13 behavior:
image

No gap fillers either.

**Comment by BagelOrb** [comment]
This PR has already been implemented in CURA-8067.

However, it is still unclear whether we want the behavior in the first place, given the bug noted by @nallath

**Comment by BagelOrb** [comment]
Checking current master there are a lot of bugs in support:
image

image

**Comment by BagelOrb** [comment]
Those disconnected segments in support might not print so well:
image

**Comment by BagelOrb** [comment]
Closing because CURA-8067 implemented the same thing.

**Pull request closed without merging**
