### PR TITLE
Bug fix - use floats to avoid loss of precision when determining sharpest corner.

### PR DESCRIPTION
**Pull request by smartavionics**
Fixes the issue discussed in https://ultimaker.com/en/community/51970-sharpest-corner-hide-seam-improvement-needed

### CODE REVIEW

**Comment by smartavionics** [comment]
It would be great if this could make it into 3.1, thanks.

**Comment by smartavionics** [comment]
Hi @ChrisTerBeke, @Ghostkeeper this really needs to go in 3.1 - please process this ASAP!

**Comment by ChrisTerBeke** [comment]
And must many other things... I don't think this will be added in the Beta, but maybe for the stable release depending on priorities, @Appesteijn ?

**Comment by smartavionics** [comment]
I just don't understand how you guys decide priorities. You only ever seem to be concerned with adding fancy features rather than producing high quality gcode. I am beginning to understand why customers get pissed off with Ultimaker.

**Comment by Appesteijn** [comment]
You don't understand or you don't agree? We are not only adding new features but also fixing a lot of bugs in every sprint. We are a little behind on the pull requests and working hard to catch up, but we do need to review and test every pull request.

**Comment by Appesteijn** [comment]
Devs: CURA-4616

**Pull request merged**
