### PR TITLE
Implement fuzzy skin outside only option.

### PR DESCRIPTION
**Pull request by smartavionics**
As discussed in https://github.com/Ultimaker/Cura/issues/2550.

### CODE REVIEW

**Comment by fieldOfView** [comment]
It looks... so simple!

**Comment by smartavionics** [comment]
> It looks... so simple!

Occam's razor and all that jazz. It appears to satisfy the people asking for it so may as well submit it for consideration.

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-7158.

**Comment by Ghostkeeper** [comment]
Works well! Thanks for the feature.

**Pull request merged**
