### PR TITLE
Multiply infill

### PR DESCRIPTION
**Pull request by BagelOrb**
Very much wow.

Self-explanatory (hopefully).

image
image
image
image
image
concentric_3d_multiply_infill
cross_3d_multiply_infill

### CODE REVIEW

**Comment by BagelOrb** [comment]
Works together with zig_zaggify_infill aka Connect Infill Lines.
See difference between first and second picture.

**Comment by Ghostkeeper** [comment]
Developers, see issue CURA-5400.

**Comment by rickyzhang82** [comment]
Great work!
Is Cura open to outsider? How can I access it?

**Comment by BagelOrb** [comment]
@rickyzhang82 Your comment seems unrelated to this PR, please create a new issue.

**Comment by rickyzhang82** [comment]
OK.

**Comment by alekseisasin** [comment]
@BagelOrb , Can you solve the merge conflict then we can start to review your pull request.

**Comment by BagelOrb** [comment]
Merge conflicts have already been solved in https://github.com/Ultimaker/CuraEngine/pull/774

If you plan to merge that PR than this one should not be merged anymore.

It could be handy for reviewing purposes to review Multiply Infill separately from Connect Infill Polygons, though.

The reason that there is a PR for both features at the same time is that they needed some rework to work together properly, but that's just 1 or 2 commits.

**Comment by alekseisasin** [comment]
So far as I understood #773, #774,#775, are connected.
This pull request has the same ticket CURA-5400 from #774, it confused me.
"If you plan to merge that PR than this one should not be merged anymore." -   I will review #774, and at the end, if everything is fine then we close this pull request without merging. If I understood correctly.

**Comment by BagelOrb** [comment]
Sounds good.

If you don't plan on reviewing this PR you might as well close it now already ;)

**Comment by jackha** [comment]
@BagelOrb Nice feature! But there seems to be tiny travels when you multiply the infill. Can you have a look at that?

cura-5399-travels

**Comment by BagelOrb** [comment]
That's very odd. However, it's a result of the order optimization, which is totally separate from the infill generation. The bug was already there, but it didn't come to the surface.

Note that this feature has been merged already.

**Comment by BagelOrb** [comment]
Ah yes. I'll make a PR for the bug fix.

**Comment by BagelOrb** [comment]
Actually there is no easy way to fix this.
I could make the wipe distance grey out, but that makes this behavior impossible, while the current behavior is not broken - it's just suboptimal.

I'll just leave it as is for now.

**Comment by jackha** [comment]
Ok thanks for looking at it.

**Pull request merged**
